[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_SUPABASE_URL = "https://pdjvxaehqhjvkbzbihvr.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkanZ4YWVocWhqdmtiemJpaHZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NzAyNjIsImV4cCI6MjA2MjI0NjI2Mn0.KCIQ9AJgOqTqBxqz86ImWeSnvusB3Pq_wqOjWIT8yJI"

[dev]
  functions = "netlify/functions"
  framework = "#custom"
  command = "vite"
  targetPort = 5173
  port = 8888

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
