[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[dev]
  framework = "vite"
  targetPort = 5173
  port = 8888
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
VITE_SUPABASE_URL=https://pdjvxaehqhjvkbzbihvr.supabase.co
VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkanZ4YWVocWhqdmtiemJpaHZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NzAyNjIsImV4cCI6MjA2MjI0NjI2Mn0.KCIQ9AJgOqTqBxqz86ImWeSnvusB3Pq_wqOjWIT8yJI
VITE_HYPERLIQUID_RPC=https://rpc.hyperliquid.xyz/evm